### ISSUE TITLE
difftime in session.c

### ISSUE THREAD

**Issue by allspace** [bagder/libssh2#1]
I guess the order of parameters in difftime function is wrong? It results negative value ...

 if (session->api_timeout > 0 &&
        (seconds_to_next == 0 ||
         seconds_to_next > session->api_timeout)) {
        time_t now = time (NULL);
        elapsed_ms = (long)(1000*difftime(start_time, now));
        if (elapsed_ms > session->api_timeout) {
            session->err_code = LIBSSH2_ERROR_TIMEOUT;
            return LIBSSH2_ERROR_TIMEOUT;
        }
        ms_to_next = (session->api_timeout - elapsed_ms);
        has_timeout = 1;
    }
    else if (ms_to_next > 0) {
        has_timeout = 1;
    }
    else
        has_timeout = 0;

**Comment by bagder** [comment]
Yes, I can only agree! Will fix.

**Comment by bagder** [comment]
Fixed in commit 20eb836f, thanks! Case closed.
